name 'jasonc-mongodb'
version '1.0.1'
source 'git://github.com/jcochard/puppet-modules/mongodb'
author 'Jason Cochard'
license 'GNU/GPLv3'
summary 'MongoDB module'
description "Install, configure, and manage mongodb from the 10gen repo."
project_page 'https://github.com/jcochard/puppet-modules/tree/master/mongodb'